language: objective-c
script: bundle exec rake
osx_image: xcode8.3

before_install:
  - curl http://curl.haxx.se/ca/cacert.pem -o /usr/local/share/cacert.pem
  - gem install bundler --no-ri --no-rdoc

install:
  - bundle install --without=documentation
